DROP TABLE ADDRESS IF EXISTS;
DROP TABLE PERSON IF EXISTS;

CREATE TABLE PERSON (
    ID INTEGER generated by default as identity (start with 1) not null,  
    FIRST_NAME varchar(50) not null,
    LAST_NAME varchar(50) not null,
	CREATED timestamp,
	CONSTRAINT IDX_PERSON_ID PRIMARY KEY (ID)
);

CREATE TABLE ADDRESS (
    ID INTEGER generated by default as identity (start with 1) not null,
    PERSON_ID integer,  
    ADDRESS varchar(255),
    CITY varchar(50) not null,
    STATE varchar(50) not null,
	CREATED timestamp,
    CONSTRAINT IDX_ADDRESS_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ADDRESS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) on delete cascade
);

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED)
   VALUES(1, 'John', 'Wilson', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, CREATED)
   VALUES(1, 1, '2 Penn Plz # 15', 'New York', 'NY', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, CREATED)
   VALUES(2, 1, '47 Howard St.', 'San Francisco', 'CA', NOW());
