server:
  port : 8081
management:
  endpoints:
    web:
       exposure:
          include : "*"
  endpoint:
    health:
#      show-details: always

spring:
  boot:
    admin:
      client:
          url: http://localhost:8082
  application:
    name: spring-rest
#  security:
#    user:
#      name: admin
#      password: password