### Use token to generate a card number

GET http://localhost:8080/create
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDI4MjM0NDMsInVzZXJfbmFtZSI6ImNhcmQiLCJhdXRob3JpdGllcyI6WyJST0xFX0NBUkRfV1JJVEUiLCJST0xFX1VTRVIiXSwianRpIjoiMzlmNTBjZDQtYjg5OC00ZGYwLWEwZjMtYmNkNzkxN2Q1OTgzIiwiY2xpZW50X2lkIjoiY2xpZW50Iiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.WayPA5Btj3PDtZ7Yk4FYJuWha18N3b4Fpu66AuSBXVcHC110O8XV9YiHSJYumVS0Kejx5SLOl3EUufqXkwmMDqmCA0_9FMKw8AEhrdnGt8wKT1DW1l1KoTOpSu_kpUfMnm-tsvAC4zj8oE8TdWOY_BryXY94uKUUEubfXydmQYlIXrO29BjRl9P-VYSs3198pySrQ8fgZeKmizpPjy_Btsah2wYrMur5GlkXt6IY_UewltXlFfYn3ghdV6gqQ_T7Zs07ELpA30KPwuOZWnYNnUAcbpuG9576vAheSrlMvBPx_-EZTPsrq9xbaDUIJrgY838LLVa8IvITbbQOpXqGvw